import 'cypress-file-upload'
import {faker} from "@faker-js/faker"

describe('tambah Skema Cabang', () => {
  it('passes', () => {
    cy.visit('https://mpower-dev.mandalafinance.com/signin')
    cy.get('#signin_nokar').type('0000031')
    cy.get('#signin_password').type('Mfin!123')
    //cy.screenshot("Login Page")
    cy.get('#signin_button').click()
    cy.wait(4000)
    cy.get('.pl-2').click()
    cy.get('.dropdown-menu-lg > :nth-child(4)').click()
    cy.get(':nth-child(1) > .selection-cell > .selection-input-4').click()
    cy.get('.btn-modal-yes').click()
    cy.get('.app-header > :nth-child(1) > .navbar-toggler > .hamburger-box').click()
    cy.get(':nth-child(6) > :nth-child(1) > .pointer').click()
    cy.get(':nth-child(6) > :nth-child(1) > .collapse > ul > :nth-child(2) > a').click()
    cy.get('.app-sidebar--header > .navbar-toggler').click()
    cy.get('.col-sm-6 > div > .mx-1').click()
    cy.get('#skema').type('Ciledug 3')
    cy.get(':nth-child(3) > .col > .d-flex > div > .text-white').click()
    cy.get(':nth-child(5) > .selection-cell').click()
    cy.get('.btn-modal-yes').click()
    cy.get(':nth-child(5) > .col > .d-flex > div > .text-white').click()
    cy.get(':nth-child(3) > .selection-cell').click()
    cy.get('.btn-modal-yes').click()
    cy.get(':nth-child(7) > .col > .d-flex > div > .text-white').click()
    cy.get(':nth-child(8) > .selection-cell').click()
    cy.get('.btn-modal-yes').click()
    cy.get('.card-footer > .btn').click()
    cy.get('.btn-modal-yes').click()
    })
})